# -*- coding: utf-8 -*-
"""
Embed the C# background-removal kernel into GammaTuner.ps1.

Why: ps2exe emits a single self-contained .exe, so at runtime there are no
bg_filter.cs / bg_trace.cs files next to the script. The kernel therefore has to
be shipped as source text inside the script and compiled with
Add-Type -TypeDefinition.

Merge rules (learned the hard way):
  * Both files declare a block-style `namespace ClearyBg`, which is additive, so
    simply concatenating the bodies is legal.
  * But `using` directives MUST precede every type declaration (CS1529), so the
    two using blocks cannot stay in place after concatenation. We hoist the
    deduped union to the top and strip them from the bodies.

Safety checks before writing:
  * ASCII only (Add-Type -TypeDefinition is fine with any encoding, but ASCII
    keeps the diff clean and rules out BOM surprises)
  * no line starting with '@ or "@  -> would terminate the here-string early
  * no `$`  -> the here-string is single-quoted so this is belt-and-braces,
              but it keeps the source safe if anyone flips it to double-quoted
  * no backtick

The patch is idempotent: the generated region is delimited by markers and is
rewritten wholesale on every run, so the .cs files stay the single source of
truth and GammaTuner.ps1 can be regenerated at any time.
"""
import hashlib
import os
import re
import sys

SRC_DIR = os.path.dirname(os.path.abspath(__file__))
PS1 = os.path.join(SRC_DIR, "GammaTuner.ps1")
CS_FILES = ["bg_filter.cs", "bg_trace.cs"]
COMBINED = os.path.join(SRC_DIR, "_kernel_combined.cs")

BEGIN = "# >>> BG_KERNEL_BEGIN  (generated by _embed_kernel.py - do not edit by hand)"
END = "# <<< BG_KERNEL_END"

ANCHOR = "try { [void][ClearyNative]::SetProcessDpiAwarenessContext([ClearyNative]::DpiPerMonitorV2) } catch {}"

USING_RE = re.compile(r"^\s*using\s+([A-Za-z_][\w.]*)\s*;\s*$")


def read_text(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    return raw.decode("utf-8-sig"), raw


def build_combined():
    usings = []
    bodies = []
    stats = []
    for name in CS_FILES:
        path = os.path.join(SRC_DIR, name)
        text, raw = read_text(path)
        lines = text.replace("\r\n", "\n").split("\n")
        keep = []
        file_usings = []
        for ln in lines:
            m = USING_RE.match(ln)
            if m:
                file_usings.append(m.group(1))
                continue
            keep.append(ln)
        for u in file_usings:
            if u not in usings:
                usings.append(u)
        body = "\n".join(keep)
        # drop leading blank lines left behind by the removed usings
        body = body.lstrip("\n")
        bodies.append(body.rstrip("\n") + "\n")
        stats.append((name, len(raw), hashlib.md5(raw).hexdigest(),
                      len(file_usings), text.count("\n") + 1))
        print("  %-14s %6d bytes  %4d lines  usings=%d  md5=%s"
              % (name, len(raw), text.count("\n") + 1, len(file_usings),
                 hashlib.md5(raw).hexdigest()[:12]))

    header = (
        "// =====================================================================\n"
        "// ClearyBg kernel - merged for inlining into GammaTuner.ps1\n"
        "// Generated by _embed_kernel.py from: " + ", ".join(CS_FILES) + "\n"
        "// using directives hoisted here: C# requires them before any type\n"
        "// declaration (CS1529), which concatenation would otherwise violate.\n"
        "// =====================================================================\n"
    )
    combined = header + "\n".join("using %s;" % u for u in usings) + "\n\n" + "\n".join(bodies)
    return combined, stats


def validate(combined):
    problems = []
    if not combined.isascii():
        bad = [i + 1 for i, l in enumerate(combined.split("\n")) if not l.isascii()]
        problems.append("non-ASCII on lines %s" % bad[:10])
    for i, ln in enumerate(combined.split("\n")):
        if ln.startswith("'@") or ln.startswith('"@'):
            problems.append("here-string terminator at line %d" % (i + 1))
        if "`" in ln:
            problems.append("backtick at line %d" % (i + 1))
    dollars = combined.count("$")
    if dollars:
        print("  note: %d '$' char(s) present (safe: here-string is single-quoted)" % dollars)
    # C# 6/7 syntax that the PS 5.1 CodeDom compiler rejects
    for pat, lbl in [(r'\$\s*"', "string interpolation"),
                     (r"\?\.", "null-conditional"),
                     (r"\?\?", "null-coalescing"),
                     (r"\bnameof\s*\(", "nameof"),
                     (r"\bout\s+var\b", "out var")]:
        hits = re.findall(pat, combined)
        if hits:
            problems.append("%s x%d" % (lbl, len(hits)))
    return problems


def build_region(combined):
    return "\n".join([
        BEGIN,
        "# ---------------------------------------------------------------------------",
        "# 去背景图像内核（纯 C#，零外部依赖，不需要 Python / numpy / 外部进程）",
        "#",
        "# 为什么内嵌源码：ps2exe 产出的是单文件 exe，运行期目录下没有 bg_filter.cs /",
        "# bg_trace.cs，因此只能用 Add-Type -TypeDefinition 从内联源码字符串编译。",
        "#",
        "# 为什么惰性编译：源码约 58KB，CodeDom 编译需要一两百毫秒，放在启动路径上会",
        "# 明显拖慢开窗；改成首次进入「画图」页时才编译，之后命中类型缓存直接返回。",
        "#",
        "# 源码经 _embed_kernel.py 校验：纯 ASCII、无 here-string 终止符、无 C# 6/7 语法。",
        "# 用单引号 here-string 装载，杜绝任何变量插值风险。",
        "# ---------------------------------------------------------------------------",
        "$script:BG_CS_SRC = @'",
        combined.rstrip("\n"),
        "'@",
        "",
        "$script:BgKernelError = ''",
        "",
        "function Initialize-BgKernel {",
        "  # 惰性编译图像内核；成功返回 $true，失败返回 $false 并把原因写进 $script:BgKernelError",
        "  if (([System.Management.Automation.PSTypeName]'ClearyBg.Bg').Type) { return $true }",
        "  try {",
        "    Add-Type -TypeDefinition $script:BG_CS_SRC -ErrorAction Stop",
        "    return $true",
        "  } catch {",
        "    $msg = ''",
        "    try { $msg = [string]$_.Exception.Message } catch {}",
        "    if (-not $msg) {",
        "      try {",
        "        $rec = $Error[0]",
        "        if ($rec -and $rec.Exception) { $msg = [string]$rec.Exception.Message }",
        "        if (-not $msg -and $rec) { $msg = [string]$rec }",
        "      } catch {}",
        "    }",
        "    if (-not $msg) { $msg = 'unknown compiler error' }",
        "    $script:BgKernelError = $msg",
        "    return $false",
        "  }",
        "}",
        END,
    ])


def main():
    print("== reading C# sources ==")
    combined, stats = build_combined()

    print("== validating merged source ==")
    problems = validate(combined)
    if problems:
        print("  FAILED:")
        for p in problems:
            print("    - " + p)
        return 1
    print("  OK  chars=%d  lines=%d" % (len(combined), combined.count("\n") + 1))

    with open(COMBINED, "wb") as fh:
        fh.write(combined.encode("ascii"))
    print("  wrote _kernel_combined.cs")

    print("== patching GammaTuner.ps1 ==")
    text, raw = read_text(PS1)
    had_bom = raw.startswith(b"\xef\xbb\xbf")
    if "\r\n" not in text:
        print("  FAILED: GammaTuner.ps1 is not CRLF")
        return 1
    norm = text.replace("\r\n", "\n")
    region = build_region(combined)

    if BEGIN in norm and END in norm:
        head, rest = norm.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        norm_new = head + region + tail
        mode = "replaced existing region"
    else:
        if ANCHOR not in norm:
            print("  FAILED: insertion anchor not found")
            return 1
        norm_new = norm.replace(ANCHOR, region + "\n\n" + ANCHOR, 1)
        mode = "inserted before DPI anchor"

    if norm_new == norm:
        print("  no change needed")
        return 0

    out = norm_new.replace("\n", "\r\n").encode("utf-8")
    if had_bom:
        out = b"\xef\xbb\xbf" + out
    with open(PS1, "wb") as fh:
        fh.write(out)
    print("  %s" % mode)
    print("  bytes %d -> %d  (+%d)" % (len(raw), len(out), len(out) - len(raw)))
    print("  new md5 = %s" % hashlib.md5(out).hexdigest())
    return 0


if __name__ == "__main__":
    sys.exit(main())
